# Generated by Django 5.2.9 on 2025-12-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('enlace', models.URLField(unique=True)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('club', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('enlace', models.URLField(unique=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='EventoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
                ('event_info', models.TextField(blank=True, null=True)),
                ('club_info', models.TextField(blank=True, null=True)),
                ('artistas', models.ManyToManyField(blank=True, related_name='eventos', to='events.artista')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='events.evento')),
                ('generos', models.ManyToManyField(blank=True, related_name='eventos', to='events.genero')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='generos',
            field=models.ManyToManyField(blank=True, related_name='artistas', to='events.genero'),
        ),
    ]
