# Generated by Django 5.2.9 on 2025-12-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='enlace',
        ),
        migrations.AddField(
            model_name='artista',
            name='eventos',
            field=models.ManyToManyField(blank=True, related_name='artistas', to='events.evento'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='eventodetalle',
            name='artistas',
            field=models.ManyToManyField(blank=True, related_name='eventos_detalle', to='events.artista'),
        ),
    ]
