# Generated by Django 6.0 on 2025-12-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_artista_enlace_artista_eventos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventodetalle',
            name='precio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
